development:
  adapter: mysql
  database: feedbackmine_dev
  host: localhost
  username: root

test:
  adapter: mysql
  database: feedbackmine_test
  host: localhost
  username: root

production:
  adapter: mysql
  database: feedbackmine
  host: localhost
  username: root

