development:
  adapter: mysql
  database: sentimenthub_dev
  host: localhost
  username: root

test:
  adapter: mysql
  database: sentimenthub_test
  host: localhost
  username: root

production:
  adapter: mysql
  database: sentimenthub
  host: localhost
  username: root

